# Generated by Django 5.1.2 on 2024-11-11 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد کد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
                'verbose_name_plural': 'رمزهای یکبار مصرف',
            },
        ),
    ]
