# Generated by Django 5.1.2 on 2024-11-18 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plan.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': 'برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='PlanAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='شرح')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_attributes', to='plan.plan', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'ویژگی برنامه',
                'verbose_name_plural': 'ویژگی های برنامه',
            },
        ),
    ]
