# Generated by Django 5.1.2 on 2024-11-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='Customer',
            new_name='customer',
        ),
    ]
